# STAGE 1: Build on Alpine (The "Heavy" part)
FROM python:3.12.12-alpine3.23 AS builder

# Install C compiler and Nuitka dependencies
RUN apk add --no-cache build-base python3-dev libffi-dev patchelf ccache

# Copy source code
WORKDIR /source
COPY ./services/sphana-rag-service/pyproject.toml .
COPY ./services/sphana-rag-service/src/python/ ./python/
COPY ./services/sphana-rag-service/src/resources ./resources/

# Install application's dependencies
# Note that "http://host.docker.internal:61000/" is the pointer to the local pypi server
RUN pip install --no-cache-dir . \
    --extra-index-url http://host.docker.internal:61000/ \
    --trusted-host host.docker.internal

# Compile to standalone
RUN python -m nuitka \
    # --mingw64 \
    --standalone \
    --onefile \
    --remove-output \
    --prefer-source-code \
    --lto=yes \
    --include-data-dir=./resources=resources \
    --output-dir=/target \
    ./python/sphana_rag

# STAGE 2: The Final Tiny Image (The "Light" part)
FROM alpine:3.23.2
WORKDIR /app/

# 1. Use the absolute path from the builder stage
# 2. Copy the specific file created by Nuitka
# On Linux, Nuitka creates <name>.bin for onefile mode
COPY --from=builder /target/sphana_rag.bin /app/sphana_rag

# 3. Ensure the binary is executable
RUN chmod +x /app/sphana_rag

# 4. Expose application's port
EXPOSE 5001

# 5. Run the application
CMD ["./sphana_rag"]